Added options to specify branches

diff --git a/cleanup-git b/cleanup-git
--- a/cleanup-git
+++ b/cleanup-git
@@ -1,12 +1,29 @@
 #!/bin/bash
 
+#options
+MAIN_BRANCH="dev"
 LOCAL_ONLY=false
-if [[ "$1" == "--local-only" ]]; then
-	LOCAL_ONLY=true
-fi
+while getopts ":b:l" opt; do
+    case $opt in
+    b)
+        MAIN_BRANCH="$OPTARG" >&2
+        ;;
+    l)
+		LOCAL_ONLY=true >&2
+		;;
+    \?)
+        echo "Invalid option: -$OPTARG" >&2
+        exit 1
+        ;;
+    :)
+        echo "Option -$OPTARG requires an argument." >&2
+        exit 1
+        ;;
+    esac
+done
 
 # Branches we don't want to remove
-keep_branches=("develop" "staging" "master" "development" "deploy")
+keep_branches=("dev" "develop" "staging" "master" "development" "deploy")
 branches_to_remove=()
 
 function safe_exit {
@@ -56,12 +73,12 @@ function do_removal {
 }
 
 current_branch=`git rev-parse --abbrev-ref HEAD`
-if [[ $current_branch != "master" ]]; then
-	exit_with_error "You need to have MASTER checked out to use this script"
+if [[ $current_branch != $MAIN_BRANCH ]]; then
+	exit_with_error "You need to have $MAIN_BRANCH checked out to use this script"
 else
-	# Get the latest from master so its on sync with the local
-	echo "Getting latest version for MASTER"
-	git pull origin master
+	# Get the latest from $MAIN_BRANCH so its on sync with the local
+	echo "Getting latest version for $MAIN_BRANCH"
+	git pull origin $MAIN_BRANCH
 
 	if [[ "$LOCAL_ONLY" = false ]]; then
 		# Fetch all remote branches so we can remove those which are in sync too
diff --git a/squashit b/squashit
--- a/squashit
+++ b/squashit
@@ -1,6 +1,27 @@
 #!/bin/bash
 
+# Check if we are squashing against dev or other base
 DEV_BRANCH="dev"
+DIFF_INDEX=""
+while getopts ":b:" opt; do
+    case $opt in
+    b)
+        DEV_BRANCH="$OPTARG" >&2
+        ;;
+    i)
+		DIFF_INDEX="$OPTARG" >&2
+		;;
+    \?)
+        echo "Invalid option: -$OPTARG" >&2
+        exit 1
+        ;;
+    :)
+        echo "Option -$OPTARG requires an argument." >&2
+        exit 1
+        ;;
+    esac
+done
+
 CURRENT_BRANCH=`git rev-parse --abbrev-ref HEAD`
 CURRENT_STATUS=`git status --porcelain`
 GIT_CHECKOUT_DEV_CMD="git checkout $DEV_BRANCH"
@@ -10,7 +31,14 @@ GIT_PULL_DEV_CMD="git pull origin $DEV_BRANCH"
 GIT_PULL_CURRENT_CMD="git pull origin $CURRENT_BRANCH"
 GIT_MERGE_CMD="git merge --no-edit $DEV_BRANCH"
 PATCH_NAME="`echo $CURRENT_BRANCH | sed 's/\//_/'`.diff"
-GIT_DIFF_CMD="git diff $DEV_BRANCH > $PATCH_NAME"
+
+if [[ $DIFF_INDEX != "" ]]; then
+	GIT_DIFF_CMD="git diff-index $DIFF_INDEX --binary > $PATCH_NAME"
+else
+	GIT_DIFF_CMD="git diff $DEV_BRANCH > $PATCH_NAME"
+fi
+
+
 GIT_RESET_HEAD_CMD="git reset --hard origin/$DEV_BRANCH"
 GIT_APPLY_PATCH_CMD="git apply $PATCH_NAME"
 GIT_ADD_CMD="git add .; git reset -- $PATCH_NAME"
@@ -30,7 +58,7 @@ function check_status {
 		echo -e "Your local branch ${BOLD_TEXT}${YELLOW_COLOR}'$CURRENT_BRANCH'${NORMAL_TEXT}${NORMAL_COLOR} is not clean, commit/discard your changes and try again"
 		exit 1
 	elif [[ $CURRENT_BRANCH == $DEV_BRANCH ]]; then
-		echo -e "You are on the ${BOLD_TEXT}${BLUE_COLOR}'$DEV_BRANCH'${NORMAL_TEXT}${NORMAL_COLOR} branch. Change to a feature branch for this script to work."
+		echo -e "You are on the ${BOLD_TEXT}${BLUE_COLOR}'$DEV_BRANCH'${NORMAL_TEXT}${NORMAL_COLOR} branch. Change to a different feature branch for this script to work."
 		exit 1
 	fi
 
